/*
 * computing_machine.h
 *
 *  Created on: 2015年5月29日
 *      Author: ron
 */

#ifndef SRC_MASTER_SLAVE_COMPUTING_MACHINE_COMPUTING_MACHINE_H_
#define SRC_MASTER_SLAVE_COMPUTING_MACHINE_COMPUTING_MACHINE_H_



#endif /* SRC_MASTER_SLAVE_COMPUTING_MACHINE_COMPUTING_MACHINE_H_ */
